name: YaMDB workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m flake8
          cd infra_project/
          python manage.py test
  

  build_and_push_to_docker_hub:

  deploy:

  send_message:
